/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package price_display;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }    
    @Test public void appDisplaysItemsWithPrice() {
        App classUnderTest = new App();
        assertEquals("Item and price are returned as a label string", String.valueOf("The price for item: coat is 50.00"), classUnderTest.getPriceLabel("coat", 50.00));
    }
}