/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package price_display;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public String getPriceLabel(String item, Double price) {
        return String.format("The price for item: %s is %,.2f", item, price);
    }
}
